const mode = "cmm"
const optimization = "O2"

const board = "-D loader=rom -D clkfreq=96000000 -D clkmode=xtal1+pll16x"
const defines = "-D ADC_EN -D SSD1306_FONT_ORBITRON"
const gcc = env("PROPGCC")

const true = 1
const false = 0

env("PATH", fmt("{0};{1}/bin", env("PATH"), gcc))

const dir = env("BSI_SOURCE_DIR")

const includes = [
    gcc + "/include/Utility/libsimpletools",
    gcc + "/include/TextDevices/libsimpletext",
    gcc + "/include/Protocol/libsimplei2c",
    gcc + "/include/Display/liboledc",
    gcc + "/include/Motor/libservo"
]

const libs = [
    "refs",
    "IO",
    "serial_buffer",
    "circular_buffer",
    "drivers/AD7812",
    "drivers/HD44780",
    "drivers/NRF24L01",
    "drivers/SSD1306",
    "fonts/orbitron_15",
    "fonts/dejavu_sans_mono_12",
    "modules/PSU",
    "modules/MCU"
]

const includeCount = count("includes")
const libCount = count("libs")

var includeDirectories = "-I . -L ."
var includeLibs = "-lm"
var obj = ""

loop i = 0 to < includeCount
    includeDirectories = fmt("{0} -I {1} -L {1}/{2}", includeDirectories, includes[i], mode)
next i + 1

loop h = includeCount to > 0
    loop i = 0 to < h
    var libName = substr(file(includes[i], false), 3)
    includeLibs = fmt("{0} -l{1}", includeLibs, libName)
    next i + 1
    includeLibs = includeLibs + " -lm"
next h - 1

loop i = 0 to < libCount
    const lib = libs[i]
    obj = fmt("{0} build/{1}.o", obj, lib)
next i + 1

func clean() global
    rmdir(dir + "/build")
    mkdir(dir + "/build")
    mkdir(dir + "/build/fonts")
    mkdir(dir + "/build/drivers")
    mkdir(dir + "/build/modules")
end

func buildFramework() global
    loop i = 0 to < libCount
        const lib = libs[i]
        print "Building library " + lib
        exec("propeller-elf-gcc", fmt("{0} -lm -{1} -m{2} -Wall -m32bit-doubles -fno-exceptions -std=c99 -c {3}/src/lib/{4}.c -o ./build/{4}.o {5}", includeDirectories, optimization, mode, dir, lib, defines))
    next i + 1
end

func build(string prog) global
    print "Building Program " + prog
    exec("propeller-elf-gcc", fmt("{0} -lm -{1} -m{2} -Wall -m32bit-doubles -fno-exceptions -std=c99 {3} src/{4}.c {5} -o ./build/{4}.elf {6}", includeDirectories, optimization, mode, obj, prog, includeLibs, defines))
    exec("propeller-load", fmt("{0} -s build/{1}.elf", board, prog))
end

func install(string prog)
    findPort()
    var port = env("PORT")
    print fmt("Installing program {0} on port {1} to EEPROM", prog, port)
    exec("proptool", fmt("--port {0} --target EEPROM --program build/{1}.binary --listen", port, prog))
end

func run(string prog)
    findPort()
    var port = env("PORT")
    print fmt("Running program {0} on port {1} on RAM", prog, port)
    exec("proptool", fmt("--port {0} --target RAM --program build/{1}.binary --listen", port, prog))
end

func check(string port)
    exec("proptool", "--check --port " + port)
end

func findPort()
    print "Finding ports..."
    rem | execute the powershell command and return the poutput into an envvar PORTS
    exec("powershell" "[System.IO.Ports.SerialPort]::getportnames()", "PORTS")
    var count = split(trim(env("PORTS"), "\r\n"), "\r\n", "ports")
    
    loop i = 0 to < count
        rem | exec proptool and send output into the void
        var ok = exec("proptool", "--check --port " + ports[i], "REDIRECT_NULL")
        if ok then
            env("PORT", ports[i])
            print "Found port " + env("PORT")
        endif
    next i + 1
    print "Done."
end
